### ISSUE TITLE
Wrong check in merge-checks

### ISSUE THREAD

**Issue by jush** [jush/refined-bitbucket#1]
I don't know how to JavaScript 😝 https://github.com/jush/refined-bitbucket/blob/simple_merge_checks/src/merge-checks/merge-checks.js#L94 is not a valid check, should check against not null

**Comment by WesleyElliott** [comment]
And I don't know Github PR tricks - but this was fixed in #2 😆

**Comment by jush** [comment]
> And I don't know Github PR tricks - but this was fixed in #2 😆

I think the PR message needs to contain `#2` in the message
